### ISSUE TITLE
"Work": "vcard:Work" prone to confusion with with WorkAction

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#105]
This mapping in current JSON-LD context might collide with potential *Work* action. Similar to [opo-actions:Working](http://online-presence.net/opo-actions/spec/#Working)

I really suggest coordinating vocabulary related work with other people interested in helping with it, preferably via [Social IG Vocabulary TF](https://www.w3.org/wiki/Socialig/Vocabulary_TF)

also

* "Contact": "vcard:Contact"
* "Friend": "vcard:Friend"
* "Date": "vcard:Date"
* "Met": "vcard:Met"

**Comment by jasnell** [comment]
There is currently no Work action defined in the core vocabulary which means there is no collision. If someone wishes to create a Work activity in the core vocabulary, they are welcome to make a proposal, otherwise it can be used as an extension with it's own fully qualified URL identifier. Closing this issue in the github tracker because it does not deal with a concrete current problem in the current spec. Feel free to open an issue in the SocialWG w3c tracker if you feel there needs to be a larger discussion.

**Comment by elf-pavlik** [comment]
I added note with link to this issue here to the [WG ISSUE-36: Role and evolution of recommended JSON-LD contexts](https://www.w3.org/Social/track/issues/36) which I already proposed for Day2 of our Face 2 Face in Paris.
I really think that we try to **solve a non existing problem** by removing 'vcard' prefix and by doing it just create more confusion!
https://lists.w3.org/Archives/Public/public-socialweb/2015Apr/0137.html
