### ISSUE TITLE
map Person to vcard:Individual and remove as:Person

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#107]
Similar to Organization, Person can map directly in JSON-LD context to vcard:Individual
http://www.w3.org/TR/vcard-rdf/#d4e1749

@jasnell unless you object I can prepare PR! I would also change this example http://www.w3.org/TR/2015/WD-activitystreams-core-20150129/#fig-an-actor-that-is-both-a-person-and-a-vcard-individual

seeAlso: https://github.com/w3c-social/social-vocab/issues/11

**Comment by jasnell** [comment]
Hmm... that would introduce a normative dependency to VCard at the vocabulary level but that's really not too big of an issue. I would still want to map the "Person" term in the JSON-LD context, largely because of historical context, but "Person" would become deprecated in favor of "Individual". I have no particular issue with that but it should be brought up for a vote. "Person" has historical precedence within Activity Streams so we'll definitely want to get the community review.

**Comment by elf-pavlik** [comment]
I thought about changing in context
{
  ...
  "Person": "vcard:Individual",
  ...
}

and *remove* http://www.w3.org/TR/activitystreams-vocabulary/#dfn-person all together just as you did removed http://www.w3.org/TR/activitystreams-vocabulary/#dfn-organization or leave it in just with vcard URI

actually while on it we could do just the same with Group

{
  ...
  "Group": "vcard:Group",
  ...
}

**Comment by jasnell** [comment]
If we did that, we'd want to explicitly mention that implementations need to treat vcard:Individual and vcard:Group as rdfs:subClassOf as:Actor. Then add equivalent statements to the non-normative vocabulary definition.

**Comment by jasnell** [comment]
Based on the WG decision to pull all external vocabularies from the AS 2.0 context, this issue no longer seems to be relevant. Closing.
