### ISSUE TITLE
Extensions of the JSON-LD context cannot be interoperable

### ISSUE THREAD

**Issue by oshepherd** [jasnell/w3c-socialwg-activitystreams#108]
Suppose the following situation:
 * A defines an extended JSON-LD context which contains term "foo"
 * B defines an extended JSON-LD context which contains term "bar"
 * C receives documents from both A and B which use their extended terms and wishes to redistribute them

If C is not a JSON-LD implementing consumer, as we expect the vast majority of ActivityStreams implementations to be, then it is not able to reconcile these differences or even reproduce them without loss of data or potential conflict.

To me it seems that the only viable approach for interoperability is that modifications of the JSON-LD context be prohibited for the "application/activitystreams+json" media type. However, this leaves the question of how to expand the ActivityStreams context without data loss unresolved (in this case, it is the JSON-LD processing clients which are problematic, not the pure JSON ones, as they will cause issues with any new context items)

**Comment by jasnell** [comment]
The spec currently does not deal much with issues related to redistribution, but, forbidding extensions is not strictly necessary here. The non-JSON-LD enabled implementation can choose to preserve and pass on the JSON-LD context used by the inputs. For instance...

Suppose C get's the following...

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {"foo": "http://example.org/foo"}
  ],
  "@type": "Note",
  "foo": 123
}
```
and
```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {"bar": "http://example.net/bar"}
  ],
  "@type": "Note",
  "bar": 321
}
```
C then redistributes both objects within a Collection document:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Collection",
  "items": [
    {
      "@context": [
        "http://www.w3.org/ns/activitystreams",
        {"foo": "http://example.org/foo"}
      ],
      "@type": "Note",
      "foo": 123
    },
    {
      "@context": [
        "http://www.w3.org/ns/activitystreams",
        {"bar": "http://example.net/bar"}
      ],
      "@type": "Note",
      "bar": 321
    }
  ]
}
```

C would not need to know any specifics about the customized contexts. It would just need to know to keep the `@context` property in tact along with the various property names when it redistributes. 

Things get a bit more complicated if C does perform JSON-LD expansion on the original documents because the `@context` is not preserved. In that case, C should snapshot the context before expansion and store it along with the expanded data so that when it serializes, it can reliably reproduce the compacted form.

**Comment by elf-pavlik** [comment]
We could also recommend establishing namespaces and prefixes for any extension intended for use outside of **certain silo**. This way ACME could register prefix for their namespace with http://prefix.cc/ and use "acme:foo" and "acme:Bar" - CURIE instead of URI.

If someone still wants to find a way to do things without namespaces, i recommend taking a look at http://microformats.org and http://schema.org and if not possible to coordinate efforts, try something similar on http://activitystrea.ms or http://activityschema.org/

Still in such case I wouldn't expect W3C preferring such newly created 'flat' namespace over two other mentioned, at least without really strong reasoning for that.

**Comment by jasnell** [comment]
Not convinced this is a problem we need to solve right now.

**Comment by jasnell** [comment]
I believe the current draft adequately addresses this concern.
