### ISSUE TITLE
Note that Activity can be used in the imperative mood

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#162]
In section 3.5 we say:
 
 > Activity objects are specializations of the base Object type that provide information about pending, ongoing or completed actions. 

It may be worthwhile to note that an Activity can also be used as a command, in the imperative mood. "Make this so."

> Activity objects are specializations of the base Object type that provide information about pending, ongoing or completed actions. They can also represent a command to cause a change in the world that makes the Activity description true.

That sounds pretty Wittgensteinian, though.

**Comment by jasnell** [comment]
I've gone back and forth on this and was never able to settle on language that worked. I'll try again.

**Comment by silverbucket** [comment]
+1 as that's almost exclusively how I use them at the moment.

**Comment by elf-pavlik** [comment]
How do I suggest/recommend someone to watch a video or read an article?

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://graph.wwelves.org/e3e7f8ab-bc4e-4036-aa8d-f2bb99c95731",
  "@type": ["Watch", "Todo"],
  "author": "https://wwelves.org/perpetual-tripper",
  "actor": "https://jasnell.me",
  "object": "https://youtu.be/3vubqzjL3fs"
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://graph.wwelves.org/bcf8dc20-ae1b-4808-93a2-2744371a1e78",
  "@type": ["Read", "Todo"],
  "author": "https://wwelves.org/perpetual-tripper",
  "actor": "https://e14n.com/evan",
  "object": "http://www.w3.org/TR/webarch/"
}
```

Maybe we can resolve *actor* vs. *author* issue by realizing that we may actually need both? @tantek 
See also: #54 #93

**Comment by csarven** [comment]
re: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/162#issuecomment-134537733

IMO, those examples don't convey (at least to me) what you want. If you look carefully (and I touched this on https://github.com/jasnell/w3c-socialwg-activitystreams/issues/93#issuecomment-134666180 ) there are two issues:

1. `author` and `actor` are misplaced. You want `author` to be actually the `actor` and `actor` the `target`.
2. `Watch` and `Todo` (likewise for the `Read` and `Todo` examples) are not super useful for machines. Okay for humans. It is unclear for the machines because they don't really know whether you meant to say that James should watch some webpage, watch *a* video that's accessible from that page, watch the primary ("the one with the largest dimensions") video, or watch the video but not audio, or...

You see, you as a human have prior knowledge to infer that something with the youtube domain and with the classes that you've picked, it means that you will get around to watch the main video that's on that URL. For a machine to "get" that, you have to describe much further.

So, either you have to add a lot more information to be clear on the exact intent of the Todo or just leave it open as a simple `Collection` of _stuff_.

**Comment by elf-pavlik** [comment]
@csarven I hope you realize that as of now WG tries to see how far we can get ignoring HTTPRange-14 issues. I will from now on use JSON-LD embedding to give resources explicit type and avoid getting into [Ceci n'est pas une pipe](https://github.com/zazukoians/trifid-ld#httprange-14-or-ceci-nest-pas-une-pipe).

I think for recommendations something like that could work better:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://graph.wwelves.org/e3e7f8ab-bc4e-4036-aa8d-f2bb99c95731",
  "@type": ["Recommend"],
  "target": "https://jasnell.me",
  "object": {
    "@type": "Watch",
    "actor": "https://jasnell.me",
    "object": {
       "@id": "https://youtu.be/3vubqzjL3fs",
       "@type": "Video"
    }
  }
}
```

I need to check if *Recommend* didn't get dropped at some point...

**Comment by jasnell** [comment]
`Recommend` is not part of the vocabulary.

**Comment by elf-pavlik** [comment]
following @dret issue [better separate grammar/vocabulary and improved spec structure](https://www.w3.org/Social/track/issues/16)

*Recommend* looks to me like candidate for something we should define, more than *Like*, *Favorite*, *View*, *Listen*, *Wach* etc. In a similar way as [as:Undo](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-undo) it offers more complex construct which one can use with **any** other Activity, which makes it in a way part of AS2.0 grammar.

I think we could just reuse [as:Offer](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-offer) here, but that could get more confusing.

I think we could search for general patterns in defining activities and only define them. Similar as in http://www.w3.org/TR/swbp-n-aryRelations/
