### ISSUE TITLE
Examples and their machine translations

### ISSUE THREAD

**Issue by csarven** [jasnell/w3c-socialwg-activitystreams#194]
Pardon me if this was previously discussed:

It is unclear to me as to what to make of the "generally equivalent, non-normative" serializations as mentioned in http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#examples . If a serialization is unable to use `as`, do they have an actual purpose in this spec? And, is it appropriate to showcase them even though their semantics are off?

If we start with the first example, http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#example-1 , it makes the statements in which, a create activity was acted by Martin, and that activity was acted on some object, an image. If we take a look at the microformats "serialization" (quotes are intentional), it does not actually make such statement - at least as far as the machines are concerned (putting NLP aside of course). The microformats statement roughly translates to: there is an entry, which has Martin as author (with their URL provided), and that same entry has a photo. I find this to be significantly different than what's intended in the example.

**Comment by jasnell** [comment]
The original intent for the alternative serializations was to provide insight into the data model using alternative syntaxes that developers may already be familiar with, as well as to show that the vocabulary can be used in a variety of contexts.

The microformats alternatives are weak because microformats currently have no defined model to express activity with the same level of granularity as AS 2.0, Microdata, RDFa or Turtle. The translation ends up being lossy. I had proposed removing the microformats examples because of that reason, but the WG opted to keep them, despite the lossiness.

**Comment by csarven** [comment]
Raised issue based on current state of things and with more details about the microformats issues: https://www.w3.org/Social/track/issues/44

**Comment by csarven** [comment]
Related issue https://github.com/jasnell/w3c-socialwg-activitystreams/issues/83

**Comment by jasnell** [comment]
Closing. There's nothing specific to do at this point.
