### ISSUE TITLE
Object partOf Collection?

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#205]
I couldn't see how to get from an Object to the Collection(s) it might be in, ie. the inverse of `items`. I saw `partOf` to indicate a CollectionPage is part of a Collection; can this be used for other objects too?

**Comment by jasnell** [comment]
We previous had a `memberOf` property but there didn't appear to be any real interest in it. I can re-add it. There's only one challenge I can see with using `partOf`... the edge case where a `CollectionPage` object is a member item of one collection but is actually a page of another collection... e.g.

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "http://example.org/collections/1",
  "@type": "Collection",
  "items": [
    {
      "@type": "CollectionPage",
      "partOf": "http://example.org/collections/2",
      ...
    }
  ]
}
```

Perhaps we just need to bring `memberOf` back?

**Comment by csarven** [comment]
I think we already have *plenty* of these terms out there and strongly caution against adding more to the pile, but rather reconsider the approach. If you must, note that `isPartOf`/`hasPart` , `member`/`memberOf` , `member`/`memberList` ... are common out there. Please don't mix and match the terminology because it becomes less obvious to track and associate both properties.

**Comment by elf-pavlik** [comment]
> There's only one challenge I can see with using partOf... the edge case where a CollectionPage object is a member item of one collection but is actually a page of another collection...

As I try to explain in #221, I see utility on the level of data model to use instances of *as:Collection* as values of *as:items*. This way *as:partOf* would naturally become *owl:inverseOf* *as:items* and also work with instances of *as:Object*.

Once again, IMO this whole CollectionPage constructs seem to make sense only on the level of **access** to the this data and [Social API spec](https://github.com/w3c-social/SocialAPI) seems like an appropriate place to address concerns of read access to data, which may also require splitting collections into multiple fragments (api pagination views) to retrieve them in multiple requests/responses each containing appropriate *api hypermedia controls* e.g. first, previous, next, last 

@jasnell could you provide a clear real world example where modeling you mentioned in a snipped would make sense?

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "http://example.org/collections/1",
  "@type": "Collection",
  "items": [
    {
      "@type": "CollectionPage",
      "partOf": "http://example.org/collections/2",
      ...
    }
  ]
}
```

**Comment by jasnell** [comment]
Nope. Like I said, it's an edge case, and not a particularly interesting one. I have no problems with using `partOf` in the way @rhiaro suggests other than the fact that no one seemed interested when `memberOf` was there providing the same functionality.

**Comment by BigBlueHat** [comment]
I do think it makes sense to move `partOf` up to `Collection` so that one could create sub-collections with or without any need to use paging. Moving it all the way up to `Object` would also accomplish that, but may invite rather complex interrelation between stream objects. Maybe. :thought_balloon:

**Comment by kevinmarks** [comment]
In practice the way this is done it to use tag on posts to mark them as part of a tag collection, so I'd suggest doing this with a matching tag on each object in the collection and the collection itself.

**Comment by BigBlueHat** [comment]
@kevinmarks tnx! Do you feel that a tag is sufficient to state that a thing is a `partOf` another thing? Rather than just tangentially related?

For instance, I could personally have the tag `coffee` but not be part of any `coffee` collection...though I drink enough to that anthropologists may think differently when they catalog my remains...
:grin: :coffee: :+1:

**Comment by BigBlueHat** [comment]
Here's the old definition of [`memberOf`](http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#dfn-memberof) fwiw:
>  Identifies a collection this object can be considered a member of 

Which had the range of `Object`.

**Comment by jasnell** [comment]
WG decision yesterday was to document a non-normative best practice to use dc:partOf if this functionality is required. Will add that to the next update.
