### ISSUE TITLE
[Proposal] Define exactly one way for "Natural Language Values"

### ISSUE THREAD

**Issue by annando** [jasnell/w3c-socialwg-activitystreams#222]
I had a look at the chapter [3.2](http://www.w3.org/TR/activitystreams-core/#naturalLanguageValues) of the specification. Now you have three different ways to implement them:

* object->displayName
* object->displaynameMap->(your language)
* object->displayName->@value (and searching for the key value with your language)

I really would propose to define **exactly** one way to do this. Having at least three different ways to do it will be nightmare for the implementers (I am one of the core developers of [Friendica](https://github.com/friendica/friendica/)).

You will need some parser to fetch every single value that had to search for one the definitions above. And if it was implemented in the last way then the system had to parse through the object to find a matching language instead of being able to directly address it. (Like you could do in the second example)

A different way could be to always access the default language via "object->displayName" (as a value that *must* be present) and *optionally* a "object->displaynameMap->..." if there are multiple languages for the data. Then an implementer can always rely on having the first value and *could* query for the optional values.

**Comment by jasnell** [comment]
Slight correction: JSON-LD provides multiple ways of implementing them, AS 2.0 specifically calls out only the first two in your list above and specifically tells implementers that they SHOULD NOT use the third. I have no problem making that a MUST NOT.

W3C i18n guidelines require that the data format have a means of identifying the language for natural language values such as displayName, content, summary etc. Since JSON does not provide those mechanisms we have to either invent them or use the JSON-LD mechanisms. 

In the original version of the Activity Streams 2.0 spec that I brought to this working group, the `displayName` value could be either a string or a language map:

```json
{
  "displayName": "Foo"
}
```

```json
{
  "displayName": {
     "en": "Foo", 
     "es": "Bar"
  }
}
```
The specification was changed to the current `displayName` and `displayNameMap` approach because of feedback on this working group that the original approach wouldn't work well with JSON-LD and that developers wouldn't like having to check to see if the value was a string or a language map.

My preference would be to return to the original plan (illustrated above) and just have the single "displayName" property whose value is either a string or an object with a map of values. It's far easier and simple both in terms of the spec and implementation. All other JSON-LD based mechanisms for expressing the value would be made a MUST NOT.

**Comment by jasnell** [comment]
Btw, I would also note that the original version of AS 2.0 that I brought had a separate `language` property used to establish the default language for an object but it was removed because it did not play well with the JSON-LD processing model... which uses the `@language` property buried in the `@context` to establish the default language. I'm perfectly happy with bringing `language` back

**Comment by annando** [comment]
Changing it from "SHOULD NOT" to "MUST NOT" sounds like a really good idea to me.

Additionally I like the idea of the single value that could be string or object/array. In PHP this is no problem. But: I can not speak for Python, Ruby, ...

**Comment by jasnell** [comment]
The challenge with using `displayName` for both forms is that it doesn't interact well with JSON-LD. For instance, consider this example in the JSON-LD Playground: http://tinyurl.com/pwcn4sd

```json
{
  "@context": {
    "as": "http://www.w3.org/ns/activitystreams",
    "displayName": {
      "@id": "as:displayName",
      "@container": "@language"
    }
  },
  "displayName": "Test"
}
```
Applying the JSON-LD expansion algorithm to this, then applying the JSON-LD compaction, you end up with the output:

```
{
  "@context": {
    "as": "http://www.w3.org/ns/activitystreams",
    "displayName": {
      "@id": "as:displayName",
      "@container": "@language"
    }
  },
  "as:displayName": "Test"
}
```
(note the addition of the `as:` prefix on the field. It's an artifact of the way the JSON-LD algorithms use the @context to produce the compacted form. We avoid that by aliasing two separate terms (`displayName` and `displayNameMap`).

**Comment by akuckartz** [comment]
Ideal would be a definition which could also be expressed using SHACL (I do not know if that is possible).

**Comment by jasnell** [comment]
WG approved the proposed changes. New editor's draft will be published shortly
