### ISSUE TITLE
Example with a series of activities using multiple vocabularies

### ISSUE THREAD

**Issue by akuckartz** [jasnell/w3c-socialwg-activitystreams#224]
Use the PR created by @csarven in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/204 to create a new one.

I will try to do that myself but probably not within the next few days.

**Comment by jasnell** [comment]
I left some additional notes in #204 pointing out places where the example needed to be fixed and explaining why the original PR could not land as is. Adding a few more examples to the appendix would be welcome but please keep in mind that the emphasis right now should be on simplifying the spec as much as possible to so that implementers have exactly what they need to implement and no more.
