### ISSUE TITLE
Clarify semantic meaning of object type Question 

### ISSUE THREAD

**Issue by rpeinl** [jasnell/w3c-socialwg-activitystreams#241]
When studying the AS 2.0 vocab spec, I was stumbling over the object type Question because my mental model was a forum with questions and answers just like specified in the respective type on [schema.org] (http://schema.org/Question). Having a look at the example, the associations that came to my mind were multiple choice questions / Learning Management Systems on the one hand and polls on the other hand. I'm not sure whether it makes sense to rename the type and / or introduce a second type for the other use case, but there should be at least a sentence in the description that avoids wrong associations in the first place.

**Comment by jasnell** [comment]
The `Question` type currently supports both. Do you have some suggested language that would be clearer?

**Comment by rpeinl** [comment]
I'm not sure what both you mean, since I actually mentioned three: Q&A, E-Learning/assessment and polls. However, I think including all different use cases in the description and/or in the examples is sufficient. Arguing over the headline is not very efficient from my perspective.

**Comment by jasnell** [comment]
My apologies, I think I read your original note too quickly and missed that you had mentioned three scenarios. I agree that some additional text around the `Question` object would be worthwhile. I'll see what I can draft up but PRs with suggested text are also welcome :+1: I'm going to relabel this as an Editorial issue rather than as a Proposal as I don't believe there's anything we actually need the WG to decide on.

**Comment by jasnell** [comment]
Addressed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253
