### ISSUE TITLE
Consider adding language property to Object or Content

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#251]
_Issue:_ 

Content objects may represent external resources, as well as via one or more representations in the `content` property.  Links may also refer to these external resources.  Both Content and Link may have `mediaType` as a property to convey the media type of the representation. Link can record the language of the content using `hrefLang`, and the embedded representations can be recorded in `contentMap`, but external content cannot currently have a language associated with it. 

_Rationale:_ 
  * Internationalization, generally. 
  * Whatever use cases support `hreflang` :) 
  * Filtering out/searching for Objects in a certain language, that aren't embedded in the stream. 
  * Possible simplification of describing the language of embedded content, when there is only one representation provided (which seems like the 99% use case)

_Proposal:_
 * Add a `language` property to Object, that has a language tag as its value.
 * Consider renaming `hrefLang` to `language` in the same way that both Link and Object can have `mediaType`
 * ~~Consider allowing `language` to be used to describe the content in `content`~~

_Examples:_
```
{
  "id": "http://example.org/index.html",
  "type": "Content",
  "mediaType": "text/html",
  "language": "fr"  // currently not possible
}
{
 "type": "Link",
 "mediaType": "text/html",
 "href": "http://example.org/index.html",
 "language": "fr" // currently called hreflang
}
{ // ignore this one
  "type": "Content",
  "mediaType": "text/html",
  "language": "fr",  // currently requires contentMap
  "content": "<html><body><span>Salut, le monde!</span></body></html>"
}
```

**Comment by azaroth42** [comment]
Per #245, the proposal also breaks the definition of mediaType as also applying to the resource with the given `id` and the literal in `content`. I am curious to know the interpretation of the first example, however.

**Comment by jasnell** [comment]
hmm.. not convinced of the value on this one and it's likely to add quite a bit of confusion. Currently, the JSON-LD way of establishing a base language context for the Object is to use `@language` in the `@context`, e.g. `{"@context": ["http://www.w3.org/ns/activitystreams", {"@language": "fr"}], "content": "Salut, le monde!"}`. Adding a `language` property at the object level has no actual impact on the Object in the JSON-LD world, which is irritating at best. Also, a single Object could contain text from multiple languages, e.g. `{"contentMap": {"en": "foo", "fr": "le foo"}}`, how would `language` work in that case?

In an earlier draft I had an Object level `language` field but chose to pull it out because of the bad interaction with the JSON-LD mechanisms. Hopefully a future version of JSON-LD will get this right but for now, I'm not sure there's much we can do.

**Comment by azaroth42** [comment]
@language in the context defines the base language for literals in the graph. [This example](http://www.w3.org/TR/json-ld/#string-internationalization) here assigns Japanese to the values of name and occupation.

What I want to do is describe the resource `http://example.org/index.html` as having content of a certain language (in this case French), in the same way that it's possible to describe an Image as having a height and width, or a Place as having latitude and longitude. 

I struck out the language-for-content bullet, as that would be a much larger change, I agree.

**Comment by jasnell** [comment]
I get what you're looking for but I'm afraid that having a `language` property is going to be confusing at best. At worst, implementers who are not following JSON-LD processing mechanisms may start to abuse it as the means of defining the global language context.

**Comment by azaroth42** [comment]
:+1: to close, given WG discussion 2015-12-02
