### ISSUE TITLE
RFC3339 requires too much artificial precision - request more flexibility

### ISSUE THREAD

**Issue by tantek** [jasnell/w3c-socialwg-activitystreams#272]
re: 1.2 Serialization Notes

One of the annoying nits with Atom that I found was its reliance on RFC3339 which basically means that all use of times MUST include seconds. In my experience it is common enough to only keep track of say, HH:MM and not HH:MM:SS that format requirements that require :SS end up just getting artificially precise :00.

Rather than cause (persist?) such data pollution, I recommend some other date-time reference, e.g. HTML5 did a lot of work with allow for coarser dates and times, for the <time> element, that allows other granularities like HH:MM and others.

**Comment by jasnell** [comment]
RFC3339 is a limited profile of the more broadly defined ISO8601. While the RFC3339 date-time construct requires the `:SS` precision, ISO8601 does not. What we can easily do here is simply say that date-times in AS2 must conform generally with the RFC3339 date-time construct but that `:SS` is optional.

Essentially, we augment the RFC3339 syntax definition (https://www.ietf.org/rfc/rfc3339.txt Section 5.6) using:
```
   as2-partial-time    = time-hour ":" time-minute [":" time-second] [time-secfrac]
   as2-full-time       = as2-partial-time time-offset
   as2-date-time       = full-date "T" as2-full-time
```
In general, I'd rather not fully adopt the HTML5 model because it allows omitting things like the date and the timezone offset. In other words, I don't believe we really have a need to support the same level of flexibility as the HTML5 time tag.

**Comment by jasnell** [comment]
Addressed in current Editor's Draft.
