### ISSUE TITLE
AS2-classes inherit from more than one parent class...

### ISSUE THREAD

**Issue by sgoendoer** [jasnell/w3c-socialwg-activitystreams#274]
I'm currently compiling a bib for AS2 and I am wondering about the inheritance structure of the classes defined in AS2 (I am referring to the "Activity Vocabulary W3C Working Draft 06 October 2015"). Two classes defined in the standard inherit from two other classes, namely 

* OrderedCollectionPage (extends OrderedCollection AND OrderedCollection)
* Question (extends Content (being a specialization of Object AND TransitiveActivity)

![model_error](https://cloud.githubusercontent.com/assets/1579152/11590748/b5cd05f4-9a92-11e5-86d7-934a568e8ab0.png)

Is this intentional? Wouldn't it be better to have OrderedCollectionPage "possessing" the parameters (partOf, next, prev) of CollectionPage and ONLY inherit from OrderedCollection? Could look like this:

![model_error_collection](https://cloud.githubusercontent.com/assets/1579152/11591223/6ba95d34-9a96-11e5-8f44-126ad2122ceb.png)

Regarding the Question, I honestly don't understand why it would be desirable to have it inheriting from Content. The working draft states that "the Question object is an Activity but the direct object is the question itself" (http://www.w3.org/TR/activitystreams-vocabulary/#dfn-question). I (kinda) do understand that a Question is something that has been started in the past and is (still) ongoing - hence the IntransitiveActivity inheritance - and I get that the Question itself is at the same time Content. But wouldn't it be more clear and useful to have a separate specialization of IntransitiveActivity (e.g. "Asking" that has a parameter "Question", which is the Question object as is (just not inheriting from IntransitiveActivity anymore)? Could look like this:

![model_error_question](https://cloud.githubusercontent.com/assets/1579152/11591262/a2aaddb2-9a96-11e5-8556-cfdd61fce02c.png)

**Comment by cwebber** [comment]
I think "Content" was or is being dropped, so that's one of these simplified.  As for the rest...

Not only is multiple inheritance possible, "composite types" are possible.  Multiple values can be held in an `@type` field and that's totally valid.  There's reason for this, though I've already explained it elsewhere.  If you're trying to model AS2 and haven't looked at it already, I suggest you read the [ActiviPy docs](http://activipy.readthedocs.org/en/latest/) to see how we model things there, and if need be, read the [http://activipy.readthedocs.org/en/latest/tutorial.html#expanding-our-vocabulary](expanding our vocabulary) section.

I'm not sure if that's helpful or totally off topic but it took me a bit to get why and how AS2'd class heierarchy works.  Hope that helps!

**Comment by jasnell** [comment]
Content is being dropped in the next WD. You can see the latest pending changes in the current Editor's Draft (http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-vocabulary/)

I'm considering changing the way the hierarchy is described in the documents a bit. The model is really a Composition model rather than classical inheritance. Essentially, everything in AS2 is either an Object or a Link. The `type` property is used to compose or layer in new types. For instance, saying `type=Note` would essentially mean this is an Object with the properties of a Note.

**Comment by jasnell** [comment]
No specific change proposal here. Closing for now. Can revisit

**Comment by rhiaro** [comment]
Hey @sgoendoer, does this answer your question? As AS2 is approaching CR, we just want to check that all the closed issues were handled okay. If you don't reply by 1300 EST Tuesday 28 June (the next WG meeting) we're going to assume you're satisfied and it will remain closed.
