### ISSUE TITLE
Why is ActivityStreams 2 so bloated? ;_;

### ISSUE THREAD

**Issue by kevinmarks** [jasnell/w3c-socialwg-activitystreams#284]
Cathal Garvey on gnusocial: 
https://quitter.no/notice/1062409
https://quitter.no/notice/1062421
https://quitter.no/notice/1062431

I'd like to implement AS2 in #Golang in order to use it as an intermediate format for data-flow processing. That is, to aggregate inputs from all sorts of different systems and convert them all into a common structure so they can be processed together for "reasons". 

ActivityStreams seems the natural choice, but because *each* ActivityStreams object or link essentially needs to be able to contain an incredible diversity of different fields, each object ends up being huge in-memory even if it only contains tiny data. 

There's also this *awful* polymorphism between datatypes that can be either links or objects, even though AS2 goes to pains to say that Links are not Objects and vice-versa, and in *either case the datatype can also be represented as a string maybe linking to the actual data*.

I think this is symptomatic of a design-by-dynamic-language, which I'd have been guilty of a few years back before playing with Go and thinking instead in structs. Maybe I'm mistaken?

Whatever the rationale was with AS2.. the result is an ambiguous, memory-inefficient representation of maybe-a-graph-maybe-a-stream that's doomed either to bugginess or robust-but-boring implementations. 

You either: 

1. Rigorously implement the spec to get the power provided by a graph-based representation, but spend most of your time avoiding bugs due to ambiguity 
2. Write a dumb "I don't know what the fuck this is please just take it" implementation that provides no power whatsoever but at least won't shatter instantly. 

..and that makes me a sad panda.

**Comment by cathalgarvey** [comment]
Ha, should have expected this to happen. :)

If I were to offer concrete suggestions to make me more comfortable with AS2:

1. If an Object/Link duality is to be part of AS2, I would strongly suggest making that duality far clearer. For example, I think it's fair to assume that Links are there to express semantic linkage between objects, in the graphing sense? So, ban string-only Links, and let it be assumed that IRI-only values in ambiguous contexts (that is, when they are assumed to represent something more than merely a string) can be assumed to link to Objects and never Links.
2. If Properties are expected to be part of only a particular subclass of Object, don't spec them as being optional on Objects; doing so leads to implementation bloat where all properties end up defined on a common root struct, bloating out that core struct's memory size, and sub-classes end up distinguished only in name and not in actual function.
3. Another way to tidy up the above would be to encourage more nesting of data. Persons are unlikely to have a useful representation of Geo data as a direct property; what does it represent? Their last known coordinates? If it represents their workplace, it should be a Geo property on a separate location object to which their person-object links, right?

I don't know, I spent a few hours working on a Go representation and ended up refactoring three times trying to figure out how to make the Link/Object and SubClasses thereof make sense in code, and eventually ragequit. I'm having similar issues with vCard, another standard that's conspicuous by its near-absence of compliant implementations; that should say a lot. At least AS2 is based on existing serialisations that are already widespread (XML/JSON) but the structure of what lies beneath the serialisation needs to make sense and be lean enough to add value over AS1.

So, more broadly, I'd also suggest asking:

1. AS1 defined a way to expand Atom to represent a broader range of "Verbs" and "Nouns", but AS2 is adding "Links" now also; now we're into graphing and deep recursive nesting. What is the desired outcome, what is the use-case and how does it differ from AS1?
2. AS1 is part of a standard that's enabled the social web (OStatus): mission partially accomplished. There are non-AS1 actions necessary for OStatus to work, such as the verby webhookery of PuSH; is it a goal of AS2 to enable in-stream notifications of subscription and deprecate PuSH? How will this be achieved and how should the spec help?
3. AS1 and AS2 are potentially valuable as interchange formats for bulk processing and data funnelling, but the representations in AS2 aren't lean enough to take full advantage of this; is it a design goal of AS2 to act as a "represent anything" interchange format?

Sorry for the brain dump. ActivityStreams is, by nature, big picture stuff, and I'm still getting my head around it.

**Comment by cwebber** [comment]
@cathalgarvey You might be interested in looking at how ActiviPy handles the heirarchy.  It avoids the graph and also is mostly functional in its approach.

However, I don't think this is an actual "issue" and thus should be closed.  There's a lot of instead sub-issues here.  I'd suggest closing these and instead open concrete, actionable issues.  Posting a rant to an issue tracker is not helpful.

**Comment by cathalgarvey** [comment]
Welp, I know that.. so I didn't post the rant to the issue tracker. Someone already involved in the process did and I elaborated. :)

I'm happy to read your implementation, but by your own admission it achieves cleanliness by taking sides in the unfortunate dichotomy I feel AS2 presents, which I mentioned in my rant:

> 1. Rigorously implement the spec to get the power provided by a graph-based representation, but spend most of your time avoiding bugs due to ambiguity
> 2. Write a dumb "I don't know what the fuck this is please just take it" implementation that provides no power whatsoever but at least won't shatter instantly.
 
..it's hard to distil this problem into an actionable issue, but I do feel it's a problem The suggestions I made above, to ban links from being represented as bare strings and to partition properties into "Object" or "Link" but rarely/never both, would go a long way to solving the problem, though.

**Comment by cathalgarvey** [comment]
..the remaining problem, that in a struct-based language the fairly flat property heirarchy bloats in-memory representations of simple datatypes, remains; fixing that would require a more fundamental look at AS2's object heirarchy, and being more opinionated about properties. For example, the suggestion that "Person" objects shouldn't have GeoJSON data attached because, lacking bloaty semantics, it makes no sense on its own. Being opinionated and saying "Make a Place object and link to it" might be anathema to the AS2 design as-is, but I think it would improve matters. As a fellow Pythonista, I imagine you'd agree given:

```fish
~> python3 -m this | grep -n "" | egrep '(10|15)'
10:Special cases aren't special enough to break the rules.
15:There should be one-- and preferably only one --obvious way to do it.
```

**Comment by kevinmarks** [comment]
Sorry for the cross-posting - my hope was to represent the external
discussion here and have it refactored into more concrete issues - that
seemed to work in webmention.

**Comment by cathalgarvey** [comment]
@kevinmarks For my part, I don't mind. @cwebber is right that a rant isn't, per se, an issue. So, I'm offering to transmute the rant into a concrete issue: Separate Links and Objects, and consider a more opinionated heirarchy of objects. :)

**Comment by akuckartz** [comment]
Thanks for this feedback to the Social Web WG. Even rants sometimes can be helpfull :smile:

**Comment by jasnell** [comment]
@cathalgarvey ... not sure what you mean by "separate links and objects" given that they're already separate things.

I've found that it's generally best to view the structure more as composed objects than a type hierarchy. Everything is either just an Object or a Link that can take on specific characteristics via composition. Implementing such a model efficiently proves to not be too difficult.

Regarding the polymorphism, the underlying model is actually quite simply: for properties like "actor", the value is essentially an array of one or more Objects and/or Links. The fact that the value can be a string is just syntactic sugar. e.g. 

```js
{
  "type": "Like",
  "actor": "http://joe.example.org",
  "object": "http://example.org/thing"
}
```

Is simply an abbreviation for:

```js
{
  "type": "Like",
  "actor": {
    "id": "http://joe.example.org"
  },
  "object": {
    "id": "http://example.org/thing"
  }
}
```

Also, keep in mind that the syntax and vocabulary features largely follow a toolkit model -- that is, individual implementers are not expected to implement every aspect -- only the bits a pieces that make the most sense to their specific use cases. Unless someone is implementing a generic library (like my acvititystrea.ms js implementation), I wouldn't expect an implementation to accept every possible variation that is possible or valid. There's a reason that everything is optional.

**Comment by cathalgarvey** [comment]
Here's my problem with this:

> Everything is either just an Object or a Link that can take on specific characteristics via composition.

> the value is essentially an array of one or more Objects and/or Links

This kind of fast-and-loose polymorphism imposes a nasty burden on implementations that want to actually distinguish between Links and Objects meaningfully; for Go, this would mean either a two-step deserialisation (which is CPU costly and probably involves more than one allocation), or to just deserialise everything to the same struct, which means huge structs and is therefore RAM-wasteful.

If Links and Objects are basically the same thing, have massive property overlap, and can be found anywhere without strict delineation, then don't delineate. Make them the same thing and drop the "Object/Link" concept *at that level*; make "Link" a subtype of "Object" that indicates a semantic linkage. That would make implementations cleaner, at least.

However, the memory-bloat would remain a significant problem, in my opinion. While ActivityStreams could be seen as just another way to serialise someone's twitter stream, it could potentially be far more than that; an interchange representation for *events* of any kind encountered online. Imagine a meta-stream consisting of your blog, your pins, your tweets, your queets and your inbox activity, etcetera etcetera...but now, the memory bloat is starting to show. Every time you want to iterate you have to allocate these huge structs only to fill in little bits of each.

If, instead, everything was a small object at core with "bags" of extra properties based on type, deserialisation would start to make more sense in languages like go and could preserve a lot of RAM:

```go
type CoreObject struct {
  // Used as a cue for deserialisation
  Type string `json:"type"`
  // Optional but recommended
  Name string `json:"name"`
  // Should probably be an IRI. Links-as-Object-subclasses use "id" instead of href, in this model.
  ID string `json:"id"`
  // Depends on type; is either a valid subtype or a map[string]interface{} if type is unknown
  Properties interface{}
}

type Link struct {
  // Embeds CoreObject's fields, so fields that follow are "extensions" for Link
  CoreObject
  Rel       string `json:"rel,omitempty"`
  MediaType string `json:"mediaType,omitempty"`
  Hreflang  string `json:"hreflang,omitempty"`
  Height    string `json:"height,omitempty"`
  Width     string `json:"width,omitempty"`
}

type Object struct {
  CoreObject
  //etc jesus I'm not filling this in here.. Object shouldn't have *all* properties
  // at ground level, they should have more properties only on subtypes where it
  // makes sense!
}
```

One of the little-but-irritating differences between Objects and Links as currently used is that, even though they could be implemented as basically the same thing in a naive implementation, they each have their own property for the same thing: `id` vs. `href`. If Links just used `id` and the `type` property was mandatory it would drastically simplify the polymorphism problem by allowing an implementor to use `type` to impose type heirarchy and ignore things that didn't fit a stricter-than-the-spec definition of "valid"

**Comment by gobengo** [comment]
It sounds like you have two main critiques:

1. Value of some properties can be Array<Object | Link> either Objects xor Links, and it's hard to deserialize that into Go.
This lack of [Variant Types](https://en.wikipedia.org/wiki/Tagged_union) could just as easily be called a weakness of Go. And, in fact, it has and is in [the golang FAQ](https://golang.org/doc/faq#variant_types).

2. "Objects and Links ... each have their own property for the same thing: id vs. href"
They're not the same thing. Links refer (`href`) to other things. A Link doesn't have the same `id` (global identifier) as the thing to which it refers.

**Comment by jasnell** [comment]
href and id are two very different things. They both may have URLs as values but they serve two completely different purposes.

**Comment by cathalgarvey** [comment]
@gobengo Whether this is a weakness of Go or not is irrelevant; not all languages support variant types/tagged unions. Is AS2 supposed to be a universal standard, or merely an implementation in one or several languages? Good datastructure design should be independent of underlying code, if you want it to be well supported and easily interoperated with.

As to ids/hrefs, and thanks also @jasnell for this, granted: `id` need only be globally unique, and IRIs are merely the most commonly documented method of achieving this in part because of the JSON-LD connection in AS2. So superficially they are used similarly in the AS2 docs.

Again, though; variant types or no, the best way to tell apart a link from an object when deserialising AS-JSON is to check for either an `id` or a `href` property, because they appear to distinguish Objects and Links. However, when Objects *or* links are represented as bare IDs/Hrefs you lose the ability to distinguish them without pulling the resource in the string (if an IRI) and checking if it's a JSON expansion of the resource (still either an Object or a Link), or something that looks more like an externally linked resource (Link).

Explicit beats implicit in this case, I feel. Objects and Links should either be basically the same thing (base object from which either derive) or they should be more cleanly separated.

**Comment by jasnell** [comment]
A Link will *always* have `"Link"` in it's `type` property. Otherwise, it's always an Object.

e.g.
```js
{
  "type": "Link",
  "href": "http://example.org"
}
```

```js
{
  "type": ["Link", "http://example.org/extension/Foo"],
  "href": "http://example.org"
}
```

When the value appears as a string or object *without `"Link"` in the `type`, it's *always* an object.

In the following, actor and object are both Objects
```js
{
  "type": "Like",
  "actor": "http://sally.example.org",
  "object": "http://example.org/foo"
}
```

```js
{
  "type": "Like",
  "actor": {"id": "http://sally.example.org"},
  "object": {"id": "http://example.org/foo"}
}
```

In other words, the *only* type you have to consider a Link is if `"Link"` explicitly appears as a value of `type`.

**Comment by cathalgarvey** [comment]
Thank you for that; it helps to clarify how the design of AS2 expects things to be parsed and deserialised vis-a-vis polymorphism. The Go version of deserialising data like this would be a two-stage deserialisation where you first deserialise into a mini-object with only a 'Type' property, check that, and then choose what downstream object to use. You'd make lists of polymorphisms using a segregating interface and segregate-by-method on that interface to get object/lists.

The above pattern assumes, however, that the "type" property is *always present* and that if it's not, for some reason, present that there's a default course of action; either to assume "Object" or to ignore and delete a datum as badly serialised. But, the spec doesn't make this clear, and if that's how you guys wanna roll on AS2 I'd recommend making it very clear.

What I understand from what you're saying, and what I'd like to be clearer in the spec, is:

1. Objects and Links are a breath apart, and are distinguished only significantly in purpose.
2. The default case when encountering a string is to assume it's an Object. Links do not occur as bare strings.
3. When encountering a JSON-Object lacking an explicit Type property, one of the following is true:
    * Assume it is an AS2-Object
    * Ignore it

If the above were made clear in the spec, it would solve problem number one: excessive implicitness and polymorphism.

Problem number two is less severe but I still feel could really do with some work: an Object heirarchy provides an opportunity to help minimise base objects to keep their memory/database footprint tiny, helping use ActivityStreams for universal data storage and data comparison. This is a pretty big deal in my opinion: increasingly there is value to be gained in interleaving one's online and offline footprints and being able to quantify and learn from that data. Right now, proprietary platforms are increasingly doing this and doling out tiny bits of value to lock people into their ecosystems, but AS2 could offer a common interleaving standard for arbitrary event or linkage data, helping Free/Libre systems to compete and to connect into more than the sum of their parts.

If, however, the standard bloats basic objects so that storing tweets, saved links, image hrefs etcetera requires a kilobyte or more each of empty JSON or database fields, then it inherently self-limits and hampers ability to store and quickly process historical data. Sure, nobody tweets *that* much, but what about quantself data generated in AS2 format by fitness trackers, with thousands of events per day? Should each be a full Object containing a massive empty field-count, or a dedicated subclass of the basic object containing additional data fields as needed?

Sorry, more brain-dumping. Data interleaving is on my mind lately as I look at the sorry state of CRM in general, and the void of any kind of quality individual-scale CRM in the open source world.

**Comment by jasnell** [comment]
It `type` is missing, it's always an Object.

**Comment by rhiaro** [comment]
Hey @cathalgarvey, does this answer your question? As AS2 is approaching CR, we just want to check that all the closed issues were handled okay. If you don't reply by 1300 EST Tuesday 28 June (the next WG meeting) we're going to assume you're satisfied and it will remain closed.
