### ISSUE TITLE
Add 'IntransitiveActivity' to as-core section 4 (to match as-vocab)

### ISSUE THREAD

**Issue by dmitrizagidulin** [jasnell/w3c-socialwg-activitystreams#290]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

The list of [Core Classes](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-vocabulary/#types) in as-vocab mentions 8 core types, but [the Model section](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#model) of as-core lists only 7 (minus the `IntransitiveActivity` type). 
I assume we want the two sections to match.

**Comment by jasnell** [comment]
this was done largely because `IntransitiveActivity` is largely part of the extended vocabulary. But I'm good with the change either way.

**Comment by evanp** [comment]
Group agreed to this propsal

**Comment by rhiaro** [comment]
I apparently spaced out for this discussion in the f2f and have no recollection of it (just read the minutes), but I pointed this out in #260 and it sounded like it was agreed to not mention `IntransitiveActivity` at all in core, and only in vocab. So I guess what actually needed to happen is vocab is updated to not list it as 'core' only as another Activity type (rather than re-mentioning it again in core)?
