### ISSUE TITLE
Problem with the "Undo" activity

### ISSUE THREAD

**Issue by xray7224** [jasnell/w3c-socialwg-activitystreams#301]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [X] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:
Using the "Undo" activity could cause potential problems when it comes to stopping following a user, removing a like from an object, etc. There is no good mechanism for getting the activities after the fact and some social networks can't be expected to keep activities from years ago.

Example of the problem: If I follow a user and several years later decide I don't want to follow this user anymore I have to try and find the original follow activity to undo it. We discussed in the F2F that the it's reasonable for social networks to impose limits on how far back the user could go back through their feed/stream to find activities thus the user might never be able to find the follow activity to unfollow the user. The server may not even keep those around to go back for.

**Comment by jasnell** [comment]
That's not really a problem with `Undo` per se... it may change how it is used, perhaps, but it doesn't actually impact the semantics of the `Undo` activity at all.

**Comment by cwebber** [comment]
It really means that we might not be able to sufficiently *use* undo to cover all the necessary cases required to support the things that MediaGoblin and pump.io can currently do, especially if you can't find the original Create or etc activity.

That's a pretty serious issue.

**Comment by cwebber** [comment]
We could combine type with `["Undo", "Like"]` or `["Undo", "Create"]` as one possible solution.

**Comment by xray7224** [comment]
> That's not really a problem with Undo per se... it may change how it is used, perhaps, but it doesn't actually impact the semantics of the Undo activity at all.

I'd be interested in knowing the use case for `Undo` if it's not to "Unlike", "Unfollow", etc. As the specification says:
> Indicates that the actor is undoing the object. In most cases, the object will be an Activity describing some previously performed action (for instance, a person may have previously "liked" an article but, for whatever reason, might choose to undo that like at some later point in time).

It sounds like the suggested use-case is exactly what we're wanting to do.

**Comment by cwebber** [comment]
@jasnell So this *might not* be an activitystreams vocabulary issue, and we can close this assuming that you agree that this is an acceptable way to represent an "Unlike" type behavior:

```
{"type": ["Undo", "Like"],
 "object": "http://foo.example/obj/blarg/"}
```

If you think, yup!  That's an okay equivalent of an "unlike" of that *object*, then great, we can recommend that way forward in ActivityPub.  Problem solved!  If you think it might instead create confusion because that's not really a union of Like because it's the opposite of Like, then we have a real problem.

And indeed, this is a [real example from the document](https://github.com/jasnell/w3c-socialwg-activitystreams/issues):

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Collection",
  "items": [
    {
      "type": "Like",
      "actor": "http://sally.example.org",
      "id": "http://activities.example.com/1",
      "published": "2015-11-12T12:34:56Z",
      "object": {
        "type": "Note",
        "id": "http://notes.example.com/1",
        "attributedTo": "http://john.example.org",
        "content": "My note"
      }
    },
    {
      "type": "Dislike",
      "actor": "http://sally.example.org",
      "id": "http://activities.example.com/2",
      "published": "2015-12-11T21:43:56Z",
      "object": {
        "type": "Note",
        "id": "http://notes.example.com/1",
        "attributedTo": "http://john.example.org",
        "content": "My note"
      }
    }
  ]
 }
```

This example implies that in order to be able to undo an activity, you have to be able to find the original version of the activity... whether its the Like or the Follow or etc.  However, we've been encouraged heavily in ActivityPub to permit clients to not have to keep around activities together... not to mention that a client might not even have access or a way of finding what the original "Like" object was that they supplied wrapping the object!  You might have to dig and dig and dig to find it, or you might find out that the original Like object is gone, in which case you'll never be able to unlike it again.

So here are two proposals of additional examples that should be considered "acceptable" in ActivityStreams enough to resolve this.  We could do:

```
{"type": ["Undo", "Like"],
 "object": "http://foo.example/obj/blarg/"}
```

or:

```
{"type": "Undo",
 "object": {
    "type": "Like",
    "object": "http://foo.example/obj/blarg/"}}
```

Maybe the latter is closer to ActivityStreams' vision of things.

* So the request: confirm that we have a way forward with one of the two ways I've proposed above, so that we do not have to expect that clients "find" the original Like of something in order to unlike it again.
* And the proposal: Include an example of this in the ActivityStreams vocabulary document.

**Comment by jasnell** [comment]
```js
{"type": ["Undo", "Like"],
 "object": "http://foo.example/obj/blarg/"}
```
No, this is not correct because the semantics of this would be "I am undoing 'http://foo.example/org/blarg' and I am liking 'http://foo.example/org/blarg'", which does not make sense. 

To get the proper semantics you would need:

```js
{
  "type": "Undo",
  "object": {
    "type": "Like",
    "object": "http://foo.example/obj/blarg/"
  }
}
```

Which is to say, "I am undoing the liking of 'http://foo.example/obj/blarg'".

**Comment by cwebber** [comment]
Okay, that should be fine.  I'm realizing now that you don't need the original "Like" activity, because you can make a "shell" Like activity that contains no "id".  That should work ok.  Sorry it took so long to come to this realization!

Unless @xray7224 has any objections I'm closing this then.

**Comment by evanp** [comment]
I'm going to close this discussion.
