### ISSUE TITLE
New media type or application/ld+json plus profile

### ISSUE THREAD

**Issue by lanthaler** [jasnell/w3c-socialwg-activitystreams#52]
JSON-LD's media type has a profile parameter which would allow to convey the same information as a separate media type. The processing model of application/ld+json isn't changed but the document conforms to a couple of additional restrictions which are defined by the profile.

**Comment by akuckartz** [comment]
I forgot something obvious: A service can answer requests for _several_ media types. That - btw - can also help to support both non-RDF and RDF-communities at the same time.

**Comment by elf-pavlik** [comment]
@jasnell @dret could you maybe try to get some feedback from IETF on that json/*+ld proposal? You know appropriate channels much better then me :smile: 

@lanthaler since AS requires http://www.w3.org/ns/json-ld#compacted #48 i guess such eventual AS specific profile would imply also it conforming to compacted profile? Or one could use multiple values for profile parameter?

@jasnell could you share with us some some clear examples where you see using profile could come as disadvantage? I would expect people to expose their data using application/ld+json in a first place and then very likely add **additional** support for more specific AS type. Using profile parameter makes it explicit that response has conforming application/ld+json and more specifically activity, if you use separate content type, you don't get an explicit information that you get application/ld+json in your response :worried:

**Comment by dret** [comment]
i'll leave it up to @jasnell to propose a new top-level json/ media type branch on some IETF list. i would bet a lot on this not going anywhere, and personally, i am really not interested in spending time with this. my proposal would still be to pick a media type that makes it explicit that what's being represented is AS.
afaict, we are still operating under the assumption that any JSON-LD interpretation and processing is optional (that's how AS has been chartered), so to me, application/activity+json looks very much like what we're doing.

**Comment by elf-pavlik** [comment]
@dret just to clarify, do you see any use cases which require that application/activity+json response does NOT conform to JSON-LD spec? In other worlds, while we *do NOT require* JSON-LD processing, do we want it to fail if someone does try to process it as JSON-LD?

**Comment by dret** [comment]
@elf-pavlik, that's still the 90000lb gorilla in the WG debate. all i am trying to clarify right now is that we have a well-defined processing model so that everybody has the same "view" of AS. i am in favor of clean layering, but i think we're still mostly handwaving and ignoring the tricky questions of openness and extensibility when it comes to be well-defined in this department. http://dret.typepad.com/dretblog/2015/02/json-or-rdf-just-decide.html

**Comment by akuckartz** [comment]
This obviously is closely related to the information model question. @dret I have read your article with some interest. But I am still convinced that we can find a good solution which will make everybody happy.

A client can provide a server with a list of acceptable media types and a server can then decide what it serves. These media types could be requested:
- `application/activity+json`
- `application/ld+json`
- `application/json`
- `json/activity+ld`

The serialization can be identical for all these media types. Let us assume that this is what the server is doing.

Let us also assume that the client does not know anything about JSON-LD or RDF. In that case it does not seem to matter which of the four media types it receives. It is a AS2 client and expects AS2 and nothing else. If that assumption is not correct then I would like to know a relevant scenario.

The server also would not care because the serializations are identical. But there is one issue. An LDP server likely will not be aware of the two special AS2 media types. There should be a convincing reason to require these servers to know about these media types. Currently I am not aware of such a reason.

**Comment by dret** [comment]
we should try to separate these issues. the first question is what the "metamodel" of AS really is. is it some improvement/variation of AS1's JSON foundation, or is it JSON-LD and thus RDF? my claim is that it cannot reasonably be both. i have seen too many APIs trying to do the "i do not want to decide and make everybody happy" dance that @mnot describes so well, and they for sure all come out horrible, and most of them are simply broken as well. when we know what our processing model is, then we can discuss how to best signal that as a media type.

**Comment by akuckartz** [comment]
@dret Separating those issues makes sense - to some extent. In my view the main "problem" is the involvement of at least two communites with different interests. More precisely: the relative size or smallness of the intersection of those communities. The larger that intersection the better.

There was a time when some publishers of HTML-pages where very interested in correct grammar. And at the same time (most) other publishers very mainly or only interested that those pages looked nice when rendered by the most popular browsers. The situation now is that HTML5 specifies tag soup. (I suppose that the handling of media type `application/xhtml+xml` by IE - which did not support it for many years - played a significant role in this development. The advantages of XHTML therefore were not usable in a decisive time. And  XHTML 2.0 did the rest...)

In any case: I hope that "Just Decide" is not seen as a Silver Bullet ;-)

**Comment by dret** [comment]
@akuckartz, the point i am making that it is a proven recipe for disaster to try to satisfy two metamodels within the same layer. "just deciding" means that you should pick one, and probably the one that happens to have more potential adopters using it. note that i am also making the point that you can still try to make both groups happy, but then it's much better to handle that in clean layers.

**Comment by jasnell** [comment]
Close due to lack of any action or further discussion

**Comment by akuckartz** [comment]
Added to the [WG agenda on 2015-07-28](https://www.w3.org/wiki/Socialwg/2015-07-28#Activity_Streams_2):
Proposal to replace media type "application/activity+json" by "application/ld+json" plus profile => Reopen jasnell/w3c-socialwg-activitystreams#52

**Comment by akuckartz** [comment]
Material for the decision is collected here:
https://www.w3.org/wiki/Socialwg/Media_type_for_AS2

**Comment by elf-pavlik** [comment]
*application/activity+json* allows to omit JSON-LD context, but it works in interoperable way only when **no vocabulary terms used come from outside of activity streams vocabulary**. as soon as people start using microformats, schema.org or any other vocab terms, then explicit JSON-LD context becomes necessary again.

**Comment by melvincarvalho** [comment]
One open question for me is as to what defines the 'status quo'

I think from @jasnell point of view the application/activity+json is the status quo as it was inherited from AS1, tho I'm unsure it's either registered with IANA or has a great deal of usage.  

OTOH the JSON LD mime type plus profile parameter is already standardized with the W3C and a REC.  Therefore, this is clearly REC track work, and could also be considered the status quo.

One question I have is whether the W3C would want to put another JSON serialization on REC track when JSON LD is fresh and starting to gain serious traction.  I'd personally be unsure it would want to, but stranger things have happened.  I'd love to see the rationale, because the arguments for on the wiki page so far doing seem compelling.

Another point is that a file prefix has not been suggested for IANA.  Does this deserve it's own issue?

Perhaps a possible compromise might be to allow those that wish to use the JSON LD mime type to do so with wording in the spec to say application/ld+json MAY be used.  And that application/activity+json SHOULD.

**Comment by akuckartz** [comment]
Arguments in favor of `application/ld+json` are contained in the Wiki page since a long time. No arguments in favor of `application/activity+json` have beed added to it. The result of the discussion of this issue therefore should be to use `application/ld+json` in the specification.

**Comment by elf-pavlik** [comment]
I find this video from @jasnell's presentation at REST Fest 2015 an interesting overview of his approach to using just some parts of JSON-LD https://vimeo.com/142595917

I have concern about using 'applicatin/ld+json' in AS2.0, since people who will publish AS2.0 don't need to fully understand JSON-LD. This way server would respond with `application/ld+json` but very likely with very poor quality of data. I guess this issue may need to stay open for little longer.

**Comment by melvincarvalho** [comment]
@elf-pavlik the profile parameter was designed to solve this problem.  When you add the profile field you can stipulate the extra requirements of AS2 core.

Speculation as to future data quality should be off topic here, as it's an unknown without backing evidence.

**Comment by jasnell** [comment]
@melvincarvalho ... yes, but JSON-LD implementations are free to completely ignore the profile parameter and aren't required to even preserve it's value in any way. I agree that it has it's uses, but as an optional parameter, the profile cannot be authoritative or normatively relied upon.

**Comment by akuckartz** [comment]
@jasnell I do not understand your last comment.

> The profile parameter MAY be used by clients to express their preferences in the content negotiation process. If the profile parameter is given, a server SHOULD return a document that honors the profiles in the list which are recognized by the server. 
http://www.w3.org/TR/json-ld/#iana-considerations

**Comment by melvincarvalho** [comment]
Perhaps @msporny could clarify further

**Comment by jasnell** [comment]
@akuckartz ... what part isn't clear? There's nothing that says implementations MUST pay attention to or preserve the profile parameter. It says it MAY be used and that servers SHOULD return content that "honors" the profile but it doesn't say anything about the server being required to specify the profile in the returned media type; it doesn't say anything about the clients being required to pay attention to it; it doesn't say anything about any uses other than in simple content negotiation. Dependency on unspecified use is unreliable.

**Comment by melvincarvalho** [comment]
@jasnell I think maybe it has to be this way.  Because, at least initially, not all JSON LD servers will start off supporting AS2.  But you can write in the AS2 spec that all AS2 compliant servers MUST preserve the profile parameters.  

The same is the case of sending the mime type application/activity+json to a server that doesnt understand it.  There is no way you can ensure you'll get back AS2.

I may be wrong on this point, but that is how I was interpreting the text.

**Comment by bblfish** [comment]
This is a new version of a debate that happened at the IETF 10 years ago. The [IETF Atom Syndication format](https://www.ietf.org/rfc/rfc4287.txt) decided for reasons of syntactic purity to not have their syntax have an RDF interpretation.  At the time the RDF tools were a lot less advanced than now, and I  don't think anybody was thinking of JS in the browser for serious tasks. As a result though the extensibility story of Atom was pretty horrible, and also the debates about the vocabulary lasted for ever and were extreemly tedious. Should something be an attribute or a tag element?  Does one need a new media type for each change to the document? ...

A few years later the big XML furore started loosing steam, then in 2012 Twitter stopped using Atom and moved to JSON. Had they worked with RDF semantically, moving to json could have been a minor adjustement - just an additional content negotiation away. As I understand Activity Streams emerges from this story, and 10 years later this same debate is going on. Do you try to satisfy people who don't understand anything ( the so called "users" ) or do you work on a good extensible architecture that will weather all fashions?

**Comment by akuckartz** [comment]
I agree with the previous comment by @bblfish. Profiles can not completely solve the Crystalisation issue. But they are better than creating new Media Types all the time. And maybe they can become a hook for implementing improved crystalisation in the future.

I also agree with this statement by @melvincarvalho 
> But you can write in the AS2 spec that all AS2 compliant servers MUST preserve the profile parameters. 

Does anybody think that this can not be done in a webby way? See the discussion in https://github.com/w3c/web-annotation/issues/51 regarding (not) constraining HTTP.

**Comment by bblfish** [comment]
I suppose if one accepts the notion of a crystallisation, then there remain the following problems:

1. how does a client actually ask for that crystallisation? After all it may be that the client just does not have the RDF tools.
2. How can one build a server to automatically return any number of crystallisations? One does not want to write LDP/SoLiD servers that have to be hard coded for each different data format.

So one way to go is a new mime type. But that creates extensibility issues and hides the underlying RDF nature of the crystallisation. Here I think that @dret 's [profile link relation type](https://www.ietf.org/rfc/rfc6906.txt) or something like that can be useful. It would actually need to be a link to a URL that is dereferenceable, so that as different crystallisation forms become popular, the server can learn about them.

so here the mime type would be: application/json+ld;profile="http://w3.org/as2/profile" 

And one would like there to be a description of that crystallisation at that location ( or a redirect to a file on some distributed database ). The URL could actually be a distributed hash table URL, to avoid denial of service attacks. It would be perfect if this could be made to tie in with the 3 types of profiles defined by @msporny's json-ld .

**Comment by elf-pavlik** [comment]
I see one potential problem with using profile instead of media type. In HTML one could use alternate relation to point to AS2.0 JSON version of content

```
<link rel="alternate" type="application/activity+json>
```

AFAIK above does not provide mechanism to specify profile, this way clients who only support AS2.0 but do NOT support full JSON-LD would need to follow

```
<link rel="alternate" type="application/ld+json>
```
and make request to try if server supports AS2.0 profile

**Comment by akuckartz** [comment]
@elf-pavlik What is the use case behind that alleged problem?

**Comment by elf-pavlik** [comment]
@akuckartz it could possibly provide a clan way for static pages to advertise where to find AS2.0 version of their content https://www.w3.org/Social/track/issues/24 WG didn't committed to pay extra attention to it but I still try to see if we can incorporate static pages into social web ecosystem.

**Comment by akuckartz** [comment]
@elf-pavlik If that use case became a requirement it should be possible to use an HTML-attribute for the profile.

But it seems that the profile can simply be included in the `type`-Attribute:

> In particular, a valid MIME type may include MIME type parameters.
http://www.w3.org/TR/html5/infrastructure.html#valid-mime-type

**Comment by elf-pavlik** [comment]
@jasnell While systems **publishing** AS2.0 need more knowledge than what one finds in plain JSON-LD spec, does JSON-LD aware systems **consuming** AS2.0 also need some additional knowledge from AS2.0 specs? (assuming we deep explicit JSON-LD context in payload)

if NO - application/ld+json allows JSON-LD aware systems to consume it without even knowing anything specific about AS2.0 media type or profile
if YES - consuming applications need to implement something specific for AS2.0, so if they need to recognize profile than they can as well recognise media type

**Comment by msporny** [comment]
Have you guys considered application/ld+json+activitystreams? Isn't that the way you're supposed to subtype?

I'm still supportive of using the profile parameter instead, but if you do decide to mint a new MIMEtype, why aren't you saying that the data is basically application/ld+json plus a few constraints?

**Comment by melvincarvalho** [comment]
@msporny great idea and comment, I've added this to the wiki:

https://www.w3.org/wiki/Socialwg/Media_type_for_AS2

Please feel free to add more points.

**Comment by jasnell** [comment]
@msporny ... unfortunately most media type parser implementations have issues with the double + suffix. Many drop the second suffix entirely and do not make it available to developers to see at all.

**Comment by BigBlueHat** [comment]
@msporny I think it'd be the other way around: `applicaiton/activitystreams+ld+json` as `json` is the foundational processing model, not `activitystreams` (which, afaik, doesn't have a different processing model other than JSON-LD or JSON).

In the Annotation WG F2F last week at TPAC, @azaroth42 and I were trending toward using `application/ld+json;profile=http://www.w3.org/ns/anno.jsonld` (where the `profile` value is also the value of `@context` within the document).

The data model for Annotations is RDF. The processing model SHOULD be JSON-LD, but MAY be JSON...if you know what the "magic strings" mean in the appropriate keys and values.

The expectation is that the response body will be a JSON-LD document matching the compacted form based on `http://www.w3.org/ns/anno.jsonld` as the context.

That seems to match what ActivityStreams 2.0 is and does also--JSON-LD that MAY be treated as JSON with it's terms (regardless) defined within a specific context file expressed in JSON-LD.

We'll be monitoring progress here (and plan to report back also) as we discover more.

Thanks!

**Comment by jasnell** [comment]
Compromise proposal: The spec can be updated to indicate that implementers SHOULD treat `application/ld+json; profile="http://www.w3.org/ns/activitystreams"` as being equivalent to `application/activity+json`. Not a MUST because there will be implementations that do not perform any JSON-LD processing at all and those should not be forced to indicate support for media type they do not actually support. For implementations that choose the full JSON-LD/RDF path, however, this equivalency gives them a path forward.

**Comment by azaroth42** [comment]
Given WG discussion regarding situations where valid AS2 documents can be invalid JSON-LD documents, +1 to activity+json with an equivalent profile.  Propose that the features that would be lost when converting to JSON-LD be called out in some documentation, perhaps where ever the profile is defined.

**Comment by cwebber** [comment]
@azaroth42 I agree, I think that given the call today, @jasnell's suggestion there is the best way forward.

However, it would be good to know, what properties of AS2 might break under a pure json-ld expansion with implied vocabulary?  GeoJSON is one.  What are any others?

It would be a big win if we could figure out how to solve those, or at least know if they could be solved.  Regarding the GeoJSON challenge of encoding issue (lists of lists) [json-ld has some proposals on how to move forward](https://github.com/json-ld/json-ld.org/issues/397).

**Comment by melvincarvalho** [comment]
Yes, it would be good to document somewhere (maybe the wiki?) the list of things in AS2 that break interop with JSON LD.  It might just make sense for the smaller deployment to align with the bigger.

**Comment by jasnell** [comment]
None of the core vocabulary properties break with JSON-LD. AS2, however, does allow for extensions (such as GeoJSON) that are not JSON-LD compatible and currently warns against their use for exactly that reason (that's why the `Place` object has properties defined for instance). Even with those warnings, however, such non-JSON-LD compatible extensions are permitted under the AS2 "must ignore" policy for extensions that an implementation may not understand and implementations are required not to throw an error if such things are found.

**Comment by melvincarvalho** [comment]
Great that's pretty good news, and the JSON LD 1.1 may solve this use case.

I've added those comments to the wiki.  What's missing is the section on the application/activity+json interop consideration (if there are any right now)

Looking roughly at the views, there's about 

* 7 with arguments for application/ld+json
* 1 with arguments for application/activity+json
* 1 with arguments for both

Approximately 20 deployments using JSON LD documented.  

Personally I dont feel strongly to +1 or -1 this.Id say consensus is leaning towards LD + profile param.  Appreciate @jasnell gesture to compromise.  It's something I could live with.

Please add extra info to the wiki if you have it.

**Comment by jasnell** [comment]
See PR #243

**Comment by akuckartz** [comment]
I appreciate the attempt of a compromise.

But I am not convinced. AS2 documents can not become invalid JSON-LD documents. That might sound paradox, but the only issue is that information might be lost by interpreting them as RDF triples.

JSON-LD does not require that all JSON data results in RDF triples. One can even construct pathological examples where a large JSON-LD document when interpreted as RDF is equivalent to zero triples.

That would be bad for LD users and SHOULD be avoided, but I do not see how a media type different from `application/ld+json` can prevent that.

**Comment by jasnell** [comment]
The media type does not prevent anything. It communicates the specific expectations, that is all. The compromise approach of treating the two as being equivalent ought to be enough to address the concern that has been raised.

**Comment by akuckartz** [comment]
@jasnell wrote:

> None of the core vocabulary properties break with JSON-LD. AS2, however, does allow for extensions (such as GeoJSON) that are not JSON-LD compatible and currently warns against their use for exactly that reason (that's why the Place object has properties defined for instance). Even with those warnings, however, such non-JSON-LD compatible extensions are permitted under the AS2 "must ignore" policy for extensions that an implementation may not understand and implementations are required not to throw an error if such things are found.

This is a flawed argument. As already stated: GeoJSON is _not_ JSON-LD incompatible. In any case a JSON-LD profile can "communicate specific expectation". Therefore this is yet another non-argument in favor of a specific new media type.

I would really like to understand why a specific media type would make sense and I am definitely prepared to change my mind. So far I have not seen any reason to do so.

**Comment by jasnell** [comment]
```json
{
  "@context": {
    "@vocab": "_:",
  },
"type": "MultiLineString",
    "coordinates": [
        [ [100.0, 0.0], [101.0, 1.0] ],
        [ [102.0, 2.0], [103.0, 3.0] ]
      ]
}
```

When run through JSON-LD expansion, yields:
```json
[
  {
    "_:coordinates": [
      {
        "@value": 100
      },
      {
        "@value": 0
      },
      {
        "@value": 101
      },
      {
        "@value": 1
      },
      {
        "@value": 102
      },
      {
        "@value": 2
      },
      {
        "@value": 103
      },
      {
        "@value": 3
      }
    ],
    "_:type": [
      {
        "@value": "MultiLineString"
      }
    ]
  }
]
```

Which, when compacted again results in : 
```json
{
  "@context": {
    "@vocab": "_:"
  },
  "coordinates": [
    100,
    0,
    101,
    1,
    102,
    2,
    103,
    3
  ],
  "type": "MultiLineString"
}
```
Which is obviously incorrect. The JSON-LD spec is quite clear that Arrays of Arrays are not valid in JSON-LD and example above shows that the JSON-LD algorithms are not capable of properly handling them. 

I'm not trying to get you to change your mind. The compromise that I have proposed allows implementers to treat `application/ld+json; profile="http://www.w3.org/ns/activitystreams"` as being equivalent to the `application/activity+json` media type.

**Comment by akuckartz** [comment]
@jasnell That is more interesting than I expected. The JSON-LD spec contains this sentence in a "NOTE":
> List of lists in the form of list objects are not allowed in this version of JSON-LD.
http://www.w3.org/TR/json-ld/#sets-and-lists

But that section is
- _non-normative_ and
- referring to "list objects"

I will have a look at the example separately.

**Comment by akuckartz** [comment]
The issue in the example is not the list of lists but the combination with a JSON-LD context which tries to interpret that list of lists. Expanding that JSON-LD document without that context (or with a context for "type" only) works properly.

**Comment by jasnell** [comment]
"works properly" *only* in the sense that the "coordinates" property is ignored entirely and dropped from the expanded result. I wouldn't exactly call that "compatible". The JSON-LD algorithms quite clearly are not designed to handle arrays of arrays, regardless of how the `@context` is defined.

**Comment by akuckartz** [comment]
@jasnell I doubt that there exists any JSON-LD user or supporter who is not unhappy with that situation.

But the current issue is about the choice between creating a new media type and using `application/ld+json`plus profile. I still do not see how the "list of lists" problem is an argument in favor of a new media type or against the `application/ld+json`plus profile.

**Comment by melvincarvalho** [comment]
Good point about coordinates and lists of lists.

Do any of the user stories rely on this functionality?

**Comment by jasnell** [comment]
WG decided to accept the proposal to use `application/activity+json` as the media type and say that implementers SHOULD treat `application/ld+json; profile="http://www.w3.org/ns/activitystreams#"` as equivalent.

**Comment by melvincarvalho** [comment]
Thanks for everyone that contributed tho this discussion.

I suggest keeping the wiki page updated where possible as implementations progress

https://www.w3.org/wiki/Socialwg/Media_type_for_AS2

Casual observations (and this may be incorrect) of the gathered data, may lead one to believe that application/ld+json implementations significantly outnumber those of application/activity+json.  I suspect we will know more in the fullness of time.  

The WG may wish to consider marking application/activity+json at risk in case it fails to get the required traction, and then falling back to the existing REC may save time.  Just a thought.
