### ISSUE TITLE
Reciprocal types: Offer/Demand, Give/Receive etc.

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#74]
http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#activity-types

defines Offer and Give, while sometimes we need the inverse types e.g.
* https://www.w3.org/wiki/Socialwg/Social_API/User_stories#Offering_asparagus
* https://www.w3.org/wiki/Socialwg/Social_API/User_stories#Demanding_help_with_the_harvest

do we have strategy for such cases?

schema.org has couple of defined ones: http://schema.org/docs/search_results.html#q=Reciprocal

**Comment by jasnell** [comment]
Currently, no. Going through the most common use cases in existing social systems I did not encounter much of this. "Demand", for instance, simply does not exist in any of the social systems that I explored. Depending on where we land with the use stories we can adjust the activity types in the core but at this point I think we need to work on consolidating as much as possible rather than expanding (just my opinion tho)

**Comment by jasnell** [comment]
Closing. If you'd like to propose adding specific new types, please submit a PR and/or open an issue in the tracker.

**Comment by silverbucket** [comment]
What are the 'use stories'? Is there somewhere I can participate and/or read them?

**Comment by silverbucket** [comment]
for reference: https://www.w3.org/wiki/Socialwg/Social_API/Sorting_user_stories
